import type { MedicationShapeId } from "./medication-shape";

const SHAPE_LABELS_EN: Record<MedicationShapeId, string> = {
	round: "Round",
	oval: "Oval",
	oblong: "Oblong",
	cylindrical: "Cylindrical",
	biconvex: "Biconvex",
	flat: "Flat",
	square: "Square",
	rectangular: "Rectangular",
	triangular: "Triangular",
	diamond: "Diamond",
	heart: "Heart",
	almond: "Almond",
	capsule: "Capsule",
	"oral-solution": "Oral solution",
	"oral-suspension": "Oral suspension",
	syrup: "Syrup",
	"oral-drops": "Oral drops",
	emulsion: "Emulsion",
	"injectable-solution": "Injectable solution",
	"injectable-suspension": "Injectable suspension",
	"powder-injection": "Powder for injection",
	"eye-drops": "Eye drops",
	"ear-drops": "Ear drops",
	"nasal-drops": "Nasal drops",
	mouthwash: "Mouthwash",
	cream: "Cream",
	ointment: "Ointment",
	gel: "Gel",
	balm: "Balm",
	lotion: "Lotion",
	mousse: "Mousse",
	paste: "Paste",
	"ophthalmic-gel": "Ophthalmic gel",
	"vaginal-gel": "Vaginal gel",
	"rectal-gel": "Rectal gel",
	"metered-aerosol": "Metered aerosol",
	"nasal-spray": "Nasal spray",
	"dry-powder-inhaler": "Dry powder inhaler",
	nebulization: "Nebulization",
	"medical-gas": "Medical gas",
	"oral-spray": "Oral spray",
	lozenge: "Lozenge",
	"sublingual-tablet": "Sublingual tablet",
	"orodispersible-film": "Orodispersible film",
	"transdermal-patch": "Transdermal patch",
	"cutaneous-device": "Cutaneous device",
	nanoparticles: "Nanoparticles",
	microspheres: "Microspheres",
	"controlled-release": "Controlled release",
	biologics: "Biologics",
};

const MEDICATION_SHAPE_GROUPS_EN: Array<{
	title: string;
	items: MedicationShapeId[];
}> = [
	{
		title: "Solid",
		items: [
			"round",
			"oval",
			"oblong",
			"cylindrical",
			"biconvex",
			"flat",
			"square",
			"rectangular",
			"triangular",
			"diamond",
			"heart",
			"almond",
			"capsule",
		],
	},
	{
		title: "Oral route",
		items: [
			"oral-solution",
			"oral-suspension",
			"syrup",
			"oral-drops",
			"emulsion",
		],
	},
	{
		title: "Injectable route",
		items: ["injectable-solution", "injectable-suspension", "powder-injection"],
	},
	{
		title: "Other liquids",
		items: ["eye-drops", "ear-drops", "nasal-drops", "mouthwash"],
	},
	{
		title: "Semi-solid",
		items: [
			"cream",
			"ointment",
			"gel",
			"balm",
			"lotion",
			"mousse",
			"paste",
			"ophthalmic-gel",
			"vaginal-gel",
			"rectal-gel",
		],
	},
	{
		title: "Gaseous / inhaled",
		items: [
			"metered-aerosol",
			"nasal-spray",
			"dry-powder-inhaler",
			"nebulization",
			"medical-gas",
		],
	},
	{
		title: "Oromucosal",
		items: [
			"oral-spray",
			"lozenge",
			"sublingual-tablet",
			"orodispersible-film",
		],
	},
	{
		title: "Transdermal",
		items: ["transdermal-patch", "cutaneous-device"],
	},
	{
		title: "Special",
		items: ["nanoparticles", "microspheres", "controlled-release", "biologics"],
	},
];

export { MEDICATION_SHAPE_GROUPS_EN, SHAPE_LABELS_EN };
